#-------------------------------
# Site Settings
title: Jay's Cookbook
logo: # You can add own logo. For example '/images/logo.png'.
description: Menca personal blogging theme for Jekyll
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Author Settings
author:
  author__name: Jay Kim
  author__bio: Web development, data engineering for human for the Earth. I share posts, free resources and inspiration.
  author__avatar: '/images/my_profile.png'

social:
- {icon: "ion-logo-twitter", link: "https://twitter.com"}
- {icon: "ion-logo-facebook", link: "https://facebook.com"}
- {icon: "ion-logo-instagram", link: "https://instagram.com"}
- {icon: "ion-logo-pinterest", link: "https://pinterest.com"}
- {icon: "ion-logo-youtube", link: "https://youtube.com"}

# Example of adding a new link to the footer - {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Hero Settings
hero:
  hero__title: Hey, I’m Jay Kim
  hero__description: Web development, data engineering for human for the Earth. I share posts, free resources and inspiration.
  hero__image: '/images/my_profile.png'


#-------------------------------
# Newsletter
mailchimp: enable # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp__identifier: frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
mailchimp__input__text: Subscribe here
mailchimp__button__text: Get a new tip


#-------------------------------
# Gallery Footer Section
gallery:
  gallery__title:
  gallery__columns: 3
  gallery__images:
    - alt: 'Rest'
      url: '/images/hobby_1.jpg'
    - alt: 'Lifestyle'
      url: '/images/hobby_2.jpg'
    - alt: 'Hobby'
      url: '/images/hobby_3.jpg'
    - alt: 'Hobby'
      url: '/images/hobby_4.png'
    - alt: 'Hobby'
      url: '/images/hobby_5.png'
    - alt: 'Hobby'
      url: '/images/hobby_6.png'



#-------------------------------
# Contact Settings
contact:
  email: your@email.com # Add your email for contant form
  description: Menso comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form

# NOTE
# Menso theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: demo-menca # Add your shortname for Disqus Comment. For example demo-menca


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 9
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:path/:basename:output_ext 
      # pages를 폴더화 하려면 :path가 들어가야 하는데, 이걸 넣으면 경로가 루트부터 시작 -> /_pages/... 이렇게 해야함

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed